server:
  port: 8086

spring:
  application:
    name: frontend-service
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

